apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rj4aldt4b-nodejs
  janus-idp.io/tekton: rj4aldt4b-nodejs
  backstage.io/kubernetes-id: rj4aldt4b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rj4aldt4b-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
