apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rj4aldt4b-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rj4aldt4b-nodejs 
  name: rj4aldt4b-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rj4aldt4b-nodejs 
